# Generated by Django 5.2.15 on 2026-06-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='员工姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('birth', models.DateField(verbose_name='出生日期')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='住址')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工信息',
                'ordering': ['-id'],
            },
        ),
    ]
